qemu: Drop vm reservation changes to test if resolves build issues
qemu-i386: Unable to reserve 0x7ffff000 bytes of virtual address space at
0x1000 (Success) for use as guest address space (check your virtual memory
ulimit setting, min_mmap_addr or reserve less using -R option)

ERROR: The postinstall intercept hook 'update_gio_module_cache-nativesdk' failed

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>